services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    image: discord-frontend
    container_name: discord_frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
